// Metadatos de países: nombre, moneda e idioma oficial.
// Incluye 257 países y territorios con sus códigos ISO 3166-1 alpha-2,
// monedas ISO 4217 e idiomas ISO 639-1.
package domain

// CountryInfo contiene la información de un país: nombre, moneda e idioma.
type CountryInfo struct {
	Country  string `json:"country"`
	Currency string `json:"currency"`
	Language string `json:"language"`
}

// CountryMetadata es el mapa canónico de códigos de país a CountryInfo.
// Cubre 257 países y territorios dependientes.
var CountryMetadata = map[string]CountryInfo{
	"AD": {Country: "Andorra", Currency: "EUR", Language: "ca"},
	"AL": {Country: "Albania", Currency: "ALL", Language: "sq"},
	"AT": {Country: "Austria", Currency: "EUR", Language: "de"},
	"BY": {Country: "Belarus", Currency: "BYN", Language: "be"},
	"BE": {Country: "Belgium", Currency: "EUR", Language: "nl"},
	"BA": {Country: "Bosnia and Herzegovina", Currency: "BAM", Language: "bs"},
	"BG": {Country: "Bulgaria", Currency: "BGN", Language: "bg"},
	"HR": {Country: "Croatia", Currency: "EUR", Language: "hr"},
	"CY": {Country: "Cyprus", Currency: "EUR", Language: "el"},
	"CZ": {Country: "Czech Republic", Currency: "CZK", Language: "cs"},
	"DK": {Country: "Denmark", Currency: "DKK", Language: "da"},
	"EE": {Country: "Estonia", Currency: "EUR", Language: "et"},
	"FI": {Country: "Finland", Currency: "EUR", Language: "fi"},
	"FR": {Country: "France", Currency: "EUR", Language: "fr"},
	"DE": {Country: "Germany", Currency: "EUR", Language: "de"},
	"GR": {Country: "Greece", Currency: "EUR", Language: "el"},
	"HU": {Country: "Hungary", Currency: "HUF", Language: "hu"},
	"IS": {Country: "Iceland", Currency: "ISK", Language: "is"},
	"IE": {Country: "Ireland", Currency: "EUR", Language: "en"},
	"IT": {Country: "Italy", Currency: "EUR", Language: "it"},
	"XK": {Country: "Kosovo", Currency: "EUR", Language: "sq"},
	"LV": {Country: "Latvia", Currency: "EUR", Language: "lv"},
	"LI": {Country: "Liechtenstein", Currency: "CHF", Language: "de"},
	"LT": {Country: "Lithuania", Currency: "EUR", Language: "lt"},
	"LU": {Country: "Luxembourg", Currency: "EUR", Language: "fr"},
	"MT": {Country: "Malta", Currency: "EUR", Language: "mt"},
	"MD": {Country: "Moldova", Currency: "MDL", Language: "ro"},
	"MC": {Country: "Monaco", Currency: "EUR", Language: "fr"},
	"ME": {Country: "Montenegro", Currency: "EUR", Language: "sr"},
	"NL": {Country: "Netherlands", Currency: "EUR", Language: "nl"},
	"NO": {Country: "Norway", Currency: "NOK", Language: "no"},
	"PL": {Country: "Poland", Currency: "PLN", Language: "pl"},
	"PT": {Country: "Portugal", Currency: "EUR", Language: "pt"},
	"RO": {Country: "Romania", Currency: "RON", Language: "ro"},
	"RU": {Country: "Russia", Currency: "RUB", Language: "ru"},
	"SM": {Country: "San Marino", Currency: "EUR", Language: "it"},
	"RS": {Country: "Serbia", Currency: "RSD", Language: "sr"},
	"SK": {Country: "Slovakia", Currency: "EUR", Language: "sk"},
	"SI": {Country: "Slovenia", Currency: "EUR", Language: "sl"},
	"ES": {Country: "Spain", Currency: "EUR", Language: "es"},
	"SE": {Country: "Sweden", Currency: "SEK", Language: "sv"},
	"CH": {Country: "Switzerland", Currency: "CHF", Language: "de"},
	"UA": {Country: "Ukraine", Currency: "UAH", Language: "uk"},
	"GB": {Country: "United Kingdom", Currency: "GBP", Language: "en"},
	"VA": {Country: "Vatican City", Currency: "EUR", Language: "it"},
	"AG": {Country: "Antigua and Barbuda", Currency: "XCD", Language: "en"},
	"AR": {Country: "Argentina", Currency: "ARS", Language: "es"},
	"AW": {Country: "Aruba", Currency: "AWG", Language: "nl"},
	"BS": {Country: "Bahamas", Currency: "BSD", Language: "en"},
	"BB": {Country: "Barbados", Currency: "BBD", Language: "en"},
	"BZ": {Country: "Belize", Currency: "BZD", Language: "en"},
	"BM": {Country: "Bermuda", Currency: "BMD", Language: "en"},
	"BO": {Country: "Bolivia", Currency: "BOB", Language: "es"},
	"BR": {Country: "Brazil", Currency: "BRL", Language: "pt"},
	"CA": {Country: "Canada", Currency: "CAD", Language: "en"},
	"CL": {Country: "Chile", Currency: "CLP", Language: "es"},
	"CO": {Country: "Colombia", Currency: "COP", Language: "es"},
	"CR": {Country: "Costa Rica", Currency: "CRC", Language: "es"},
	"CU": {Country: "Cuba", Currency: "CUP", Language: "es"},
	"DM": {Country: "Dominica", Currency: "XCD", Language: "en"},
	"DO": {Country: "Dominican Republic", Currency: "DOP", Language: "es"},
	"EC": {Country: "Ecuador", Currency: "USD", Language: "es"},
	"SV": {Country: "El Salvador", Currency: "USD", Language: "es"},
	"GD": {Country: "Grenada", Currency: "XCD", Language: "en"},
	"GT": {Country: "Guatemala", Currency: "GTQ", Language: "es"},
	"GY": {Country: "Guyana", Currency: "GYD", Language: "en"},
	"HT": {Country: "Haiti", Currency: "HTG", Language: "fr"},
	"HN": {Country: "Honduras", Currency: "HNL", Language: "es"},
	"JM": {Country: "Jamaica", Currency: "JMD", Language: "en"},
	"MX": {Country: "Mexico", Currency: "MXN", Language: "es"},
	"NI": {Country: "Nicaragua", Currency: "NIO", Language: "es"},
	"PA": {Country: "Panama", Currency: "PAB", Language: "es"},
	"PY": {Country: "Paraguay", Currency: "PYG", Language: "es"},
	"PE": {Country: "Peru", Currency: "PEN", Language: "es"},
	"KN": {Country: "Saint Kitts and Nevis", Currency: "XCD", Language: "en"},
	"LC": {Country: "Saint Lucia", Currency: "XCD", Language: "en"},
	"VC": {Country: "Saint Vincent and the Grenadines", Currency: "XCD", Language: "en"},
	"SR": {Country: "Suriname", Currency: "SRD", Language: "nl"},
	"TT": {Country: "Trinidad and Tobago", Currency: "TTD", Language: "en"},
	"US": {Country: "United States", Currency: "USD", Language: "en"},
	"UY": {Country: "Uruguay", Currency: "UYU", Language: "es"},
	"VE": {Country: "Venezuela", Currency: "VES", Language: "es"},
	"AF": {Country: "Afghanistan", Currency: "AFN", Language: "ps"},
	"AM": {Country: "Armenia", Currency: "AMD", Language: "hy"},
	"AZ": {Country: "Azerbaijan", Currency: "AZN", Language: "az"},
	"BH": {Country: "Bahrain", Currency: "BHD", Language: "ar"},
	"BD": {Country: "Bangladesh", Currency: "BDT", Language: "bn"},
	"BT": {Country: "Bhutan", Currency: "BTN", Language: "dz"},
	"BN": {Country: "Brunei", Currency: "BND", Language: "ms"},
	"KH": {Country: "Cambodia", Currency: "KHR", Language: "km"},
	"CN": {Country: "China", Currency: "CNY", Language: "zh"},
	"GE": {Country: "Georgia", Currency: "GEL", Language: "ka"},
	"HK": {Country: "Hong Kong", Currency: "HKD", Language: "zh"},
	"IN": {Country: "India", Currency: "INR", Language: "hi"},
	"ID": {Country: "Indonesia", Currency: "IDR", Language: "id"},
	"IR": {Country: "Iran", Currency: "IRR", Language: "fa"},
	"IQ": {Country: "Iraq", Currency: "IQD", Language: "ar"},
	"IL": {Country: "Israel", Currency: "ILS", Language: "he"},
	"JP": {Country: "Japan", Currency: "JPY", Language: "ja"},
	"JO": {Country: "Jordan", Currency: "JOD", Language: "ar"},
	"KZ": {Country: "Kazakhstan", Currency: "KZT", Language: "kk"},
	"KW": {Country: "Kuwait", Currency: "KWD", Language: "ar"},
	"KG": {Country: "Kyrgyzstan", Currency: "KGS", Language: "ky"},
	"LA": {Country: "Laos", Currency: "LAK", Language: "lo"},
	"LB": {Country: "Lebanon", Currency: "LBP", Language: "ar"},
	"MY": {Country: "Malaysia", Currency: "MYR", Language: "ms"},
	"MV": {Country: "Maldives", Currency: "MVR", Language: "dv"},
	"MN": {Country: "Mongolia", Currency: "MNT", Language: "mn"},
	"MM": {Country: "Myanmar", Currency: "MMK", Language: "my"},
	"NP": {Country: "Nepal", Currency: "NPR", Language: "ne"},
	"KP": {Country: "North Korea", Currency: "KPW", Language: "ko"},
	"OM": {Country: "Oman", Currency: "OMR", Language: "ar"},
	"PK": {Country: "Pakistan", Currency: "PKR", Language: "ur"},
	"PS": {Country: "Palestine", Currency: "ILS", Language: "ar"},
	"PH": {Country: "Philippines", Currency: "PHP", Language: "tl"},
	"QA": {Country: "Qatar", Currency: "QAR", Language: "ar"},
	"SA": {Country: "Saudi Arabia", Currency: "SAR", Language: "ar"},
	"SG": {Country: "Singapore", Currency: "SGD", Language: "en"},
	"KR": {Country: "South Korea", Currency: "KRW", Language: "ko"},
	"LK": {Country: "Sri Lanka", Currency: "LKR", Language: "si"},
	"SY": {Country: "Syria", Currency: "SYP", Language: "ar"},
	"TW": {Country: "Taiwan", Currency: "TWD", Language: "zh"},
	"TJ": {Country: "Tajikistan", Currency: "TJS", Language: "tg"},
	"TH": {Country: "Thailand", Currency: "THB", Language: "th"},
	"TL": {Country: "Timor-Leste", Currency: "USD", Language: "pt"},
	"TR": {Country: "Turkey", Currency: "TRY", Language: "tr"},
	"TM": {Country: "Turkmenistan", Currency: "TMT", Language: "tk"},
	"AE": {Country: "United Arab Emirates", Currency: "AED", Language: "ar"},
	"UZ": {Country: "Uzbekistan", Currency: "UZS", Language: "uz"},
	"VN": {Country: "Vietnam", Currency: "VND", Language: "vi"},
	"YE": {Country: "Yemen", Currency: "YER", Language: "ar"},
	"AU": {Country: "Australia", Currency: "AUD", Language: "en"},
	"FJ": {Country: "Fiji", Currency: "FJD", Language: "en"},
	"KI": {Country: "Kiribati", Currency: "AUD", Language: "en"},
	"MH": {Country: "Marshall Islands", Currency: "USD", Language: "en"},
	"FM": {Country: "Micronesia", Currency: "USD", Language: "en"},
	"NR": {Country: "Nauru", Currency: "AUD", Language: "en"},
	"NZ": {Country: "New Zealand", Currency: "NZD", Language: "en"},
	"PW": {Country: "Palau", Currency: "USD", Language: "en"},
	"PG": {Country: "Papua New Guinea", Currency: "PGK", Language: "en"},
	"WS": {Country: "Samoa", Currency: "WST", Language: "en"},
	"SB": {Country: "Solomon Islands", Currency: "SBD", Language: "en"},
	"TO": {Country: "Tonga", Currency: "TOP", Language: "en"},
	"TV": {Country: "Tuvalu", Currency: "AUD", Language: "en"},
	"VU": {Country: "Vanuatu", Currency: "VUV", Language: "en"},
	"DZ": {Country: "Algeria", Currency: "DZD", Language: "ar"},
	"AO": {Country: "Angola", Currency: "AOA", Language: "pt"},
	"BJ": {Country: "Benin", Currency: "XOF", Language: "fr"},
	"BW": {Country: "Botswana", Currency: "BWP", Language: "en"},
	"BF": {Country: "Burkina Faso", Currency: "XOF", Language: "fr"},
	"BI": {Country: "Burundi", Currency: "BIF", Language: "fr"},
	"CV": {Country: "Cabo Verde", Currency: "CVE", Language: "pt"},
	"CM": {Country: "Cameroon", Currency: "XAF", Language: "fr"},
	"CF": {Country: "Central African Republic", Currency: "XAF", Language: "fr"},
	"TD": {Country: "Chad", Currency: "XAF", Language: "fr"},
	"KM": {Country: "Comoros", Currency: "KMF", Language: "ar"},
	"CG": {Country: "Congo", Currency: "XAF", Language: "fr"},
	"CD": {Country: "Congo (Democratic Republic of the)", Currency: "CDF", Language: "fr"},
	"CI": {Country: "Côte d'Ivoire", Currency: "XOF", Language: "fr"},
	"DJ": {Country: "Djibouti", Currency: "DJF", Language: "fr"},
	"EG": {Country: "Egypt", Currency: "EGP", Language: "ar"},
	"GQ": {Country: "Equatorial Guinea", Currency: "XAF", Language: "es"},
	"ER": {Country: "Eritrea", Currency: "ERN", Language: "ti"},
	"SZ": {Country: "Eswatini", Currency: "SZL", Language: "en"},
	"ET": {Country: "Ethiopia", Currency: "ETB", Language: "am"},
	"GA": {Country: "Gabon", Currency: "XAF", Language: "fr"},
	"GM": {Country: "Gambia", Currency: "GMD", Language: "en"},
	"GH": {Country: "Ghana", Currency: "GHS", Language: "en"},
	"GN": {Country: "Guinea", Currency: "GNF", Language: "fr"},
	"GW": {Country: "Guinea-Bissau", Currency: "XOF", Language: "pt"},
	"KE": {Country: "Kenya", Currency: "KES", Language: "sw"},
	"LS": {Country: "Lesotho", Currency: "LSL", Language: "en"},
	"LR": {Country: "Liberia", Currency: "LRD", Language: "en"},
	"LY": {Country: "Libya", Currency: "LYD", Language: "ar"},
	"MG": {Country: "Madagascar", Currency: "MGA", Language: "mg"},
	"MW": {Country: "Malawi", Currency: "MWK", Language: "en"},
	"ML": {Country: "Mali", Currency: "XOF", Language: "fr"},
	"MR": {Country: "Mauritania", Currency: "MRU", Language: "ar"},
	"MU": {Country: "Mauritius", Currency: "MUR", Language: "en"},
	"MA": {Country: "Morocco", Currency: "MAD", Language: "ar"},
	"MZ": {Country: "Mozambique", Currency: "MZN", Language: "pt"},
	"NA": {Country: "Namibia", Currency: "NAD", Language: "en"},
	"NE": {Country: "Niger", Currency: "XOF", Language: "fr"},
	"NG": {Country: "Nigeria", Currency: "NGN", Language: "en"},
	"RW": {Country: "Rwanda", Currency: "RWF", Language: "rw"},
	"ST": {Country: "São Tomé and Príncipe", Currency: "STN", Language: "pt"},
	"SN": {Country: "Senegal", Currency: "XOF", Language: "fr"},
	"SC": {Country: "Seychelles", Currency: "SCR", Language: "en"},
	"SL": {Country: "Sierra Leone", Currency: "SLL", Language: "en"},
	"SO": {Country: "Somalia", Currency: "SOS", Language: "so"},
	"ZA": {Country: "South Africa", Currency: "ZAR", Language: "en"},
	"SS": {Country: "South Sudan", Currency: "SSP", Language: "en"},
	"SD": {Country: "Sudan", Currency: "SDG", Language: "ar"},
	"TZ": {Country: "Tanzania", Currency: "TZS", Language: "sw"},
	"TG": {Country: "Togo", Currency: "XOF", Language: "fr"},
	"TN": {Country: "Tunisia", Currency: "TND", Language: "ar"},
	"UG": {Country: "Uganda", Currency: "UGX", Language: "en"},
	"ZM": {Country: "Zambia", Currency: "ZMW", Language: "en"},
	"ZW": {Country: "Zimbabwe", Currency: "ZWL", Language: "en"},
	"AI": {Country: "Anguilla", Currency: "XCD", Language: "en"},
	"KY": {Country: "Cayman Islands", Currency: "KYD", Language: "en"},
	"CX": {Country: "Christmas Island", Currency: "AUD", Language: "en"},
	"CC": {Country: "Cocos (Keeling) Islands", Currency: "AUD", Language: "en"},
	"CK": {Country: "Cook Islands", Currency: "NZD", Language: "en"},
	"FK": {Country: "Falkland Islands", Currency: "FKP", Language: "en"},
	"GF": {Country: "French Guiana", Currency: "EUR", Language: "fr"},
	"PF": {Country: "French Polynesia", Currency: "XPF", Language: "fr"},
	"GI": {Country: "Gibraltar", Currency: "GIP", Language: "en"},
	"GL": {Country: "Greenland", Currency: "DKK", Language: "da"},
	"GP": {Country: "Guadeloupe", Currency: "EUR", Language: "fr"},
	"GU": {Country: "Guam", Currency: "USD", Language: "en"},
	"GG": {Country: "Guernsey", Currency: "GBP", Language: "en"},
	"IM": {Country: "Isle of Man", Currency: "GBP", Language: "en"},
	"JE": {Country: "Jersey", Currency: "GBP", Language: "en"},
	"MS": {Country: "Montserrat", Currency: "XCD", Language: "en"},
	"NC": {Country: "New Caledonia", Currency: "XPF", Language: "fr"},
	"NU": {Country: "Niue", Currency: "NZD", Language: "en"},
	"NF": {Country: "Norfolk Island", Currency: "AUD", Language: "en"},
	"MP": {Country: "Northern Mariana Islands", Currency: "USD", Language: "en"},
	"PR": {Country: "Puerto Rico", Currency: "USD", Language: "es"},
	"RE": {Country: "Réunion", Currency: "EUR", Language: "fr"},
	"SH": {Country: "Saint Helena", Currency: "SHP", Language: "en"},
	"PM": {Country: "Saint Pierre and Miquelon", Currency: "EUR", Language: "fr"},
	"BL": {Country: "Saint Barthélemy", Currency: "EUR", Language: "fr"},
	"MF": {Country: "Saint Martin", Currency: "EUR", Language: "fr"},
	"UM": {Country: "United States Minor Outlying Islands", Currency: "USD", Language: "en"},
	"VG": {Country: "Virgin Islands (British)", Currency: "USD", Language: "en"},
	"VI": {Country: "Virgin Islands (U.S.)", Currency: "USD", Language: "en"},
	"WF": {Country: "Wallis and Futuna", Currency: "XPF", Language: "fr"},
}

// GetCountryInfo retorna la información de un país dado su código ISO 3166-1 alpha-2.
func GetCountryInfo(countryCode string) (CountryInfo, bool) {
	info, ok := CountryMetadata[countryCode]
	return info, ok
}

// CurrencyForCountry retorna la moneda ISO 4217 para un país.
// defaultCurrency es el valor a usar si el país no está en CountryMetadata.
func CurrencyForCountry(countryCode string, defaultCurrency string) string {
	if info, ok := CountryMetadata[countryCode]; ok {
		return info.Currency
	}
	if defaultCurrency != "" {
		return defaultCurrency
	}
	return "USD"
}

// LanguageForCountry retorna el idioma ISO 639-1 para un país, o "en" por defecto.
func LanguageForCountry(countryCode string) string {
	if info, ok := CountryMetadata[countryCode]; ok {
		return info.Language
	}
	return "en"
}
