CREATE DATABASE auth_db;
CREATE DATABASE user_db;
CREATE DATABASE reference_db;
CREATE DATABASE booking_db;
CREATE DATABASE payment_db;
CREATE DATABASE search_db;
CREATE DATABASE notification_db;
CREATE DATABASE audit_db;